### PR TITLE
Support for optional-only map()

### PR DESCRIPTION
**Pull request by mattbishop**
Fixes https://github.com/prayerslayer/js.spec/issues/40

### CODE REVIEW

**Comment by prayerslayer** [comment]
Very nice, thanks a ton! Would you mind adding a test case with an empty map too (the original one from the issue)?

**Comment by prayerslayer** [comment]
Released as `1.0.0-8`, thank you again!

**Comment by mattbishop** [comment]
👍

**Comment by arichiardi** [comment]
Cool

**Pull request merged**
