### PR TITLE
Use uglify-es-webpack-plugin and closes #33

### LINKED ISSUE #33: Javascript spec type not discoverable from Typescript?
Hello again @prayerslayer!

I am using `js.spec` from Typescript and, unless I am doing something silly, it looks like the `instanceof` operator is not returning true for spec passed in from modules. Don't ask me why :cry: 

Investigation has become, I will write some more things here as I discover them. Not a JS dev here, so it might be something very obvious that I wish I can quickly discover.

The part that fails in the `js.spec` code is `toSpec`, which throws all sorts of errors even if the input objects seem correct when I print them.

Have you considered using an explicit key, maybe using `Symbol` which does not interfere with the "normal" ones, for type information?

### PR DESCRIPTION
**Pull request by arichiardi**
Vanilla webpack -p uses UglifyJS to mangle names. Unfortunately UglifyJS does not yet work with ES6 classes and breaks the instanceof check in util#isSpecInstance.
Babili is ES6-capable and this patch hooks it up for the build.

### CODE REVIEW

**Comment by arichiardi** [comment]
The failure is because of the issue here: https://github.com/noBlubb/uglify-es-webpack-plugin/issues/5#issuecomment-309774834

**Comment by arichiardi** [comment]
Switched to use vanilla `webpack-uglify-plugin` and UglifyJS2 harmony

**Comment by prayerslayer** [comment]
Uh, I didn't know! Good catch :clap: Instead of Uglify I'd rather try [Babili](https://github.com/babel/babili). Because I think there's only so much you can tack on UglifyJS.

**Comment by arichiardi** [comment]
Ok cool, did not know about that, shall I use the preset? https://github.com/babel/babili/tree/master/packages/babel-preset-babili

**Comment by arichiardi** [comment]
@prayerslayer Also wanted to ask you if would you mind releasing a new version. You would make me/my team very happy :smile:

**Comment by arichiardi** [comment]
Nope that did not work, hold on this one

**Comment by arichiardi** [comment]
I am running into this: https://github.com/babel/babili/issues/556

I can leave this open in order for them to fix it and use UglifyES instead for now, what do you think?

Error:

```

ERROR in ./lib/spec/collection.js
    Module build failed: TypeError: /home/arichiardi/git/js.spec/lib/spec/collection.js: Cannot read property 'add' of undefined
        at ScopeTracker.addReference (/home/arichiardi/git/js.spec/node_modules/babel-plugin-minify-mangle-names/lib/scope-tracker.js:55:36)
        at ReferencedIdentifier (/home/arichiardi/git/js.spec/node_modules/babel-plugin-minify-mangle-names/lib/index.js:190:28)
        at newFn (/home/arichiardi/git/js.spec/node_modules/babel-traverse/lib/visitors.js:318:17)
        at bfsTraverse (/home/arichiardi/git/js.spec/node_modules/babel-plugin-minify-mangle-names/lib/bfs-traverse.js:34:43)
        at Mangler.collect (/home/arichiardi/git/js.spec/node_modules/babel-plugin-minify-mangle-names/lib/index.js:269:9)
        at Mangler.run (/home/arichiardi/git/js.spec/node_modules/babel-plugin-minify-mangle-names/lib/index.js:70:14)
        at PluginPass.exit (/home/arichiardi/git/js.spec/node_modules/babel-plugin-minify-mangle-names/lib/index.js:589:19)
        at newFn (/home/arichiardi/git/js.spec/node_modules/babel-traverse/lib/visitors.js:276:21)
        at NodePath._call (/home/arichiardi/git/js.spec/node_modules/babel-traverse/lib/path/context.js:76:18)
        at NodePath.call (/home/arichiardi/git/js.spec/node_modules/babel-traverse/lib/path/context.js:48:17)
        at NodePath.visit (/home/arichiardi/git/js.spec/node_modules/babel-traverse/lib/path/context.js:117:8)
        at TraversalContext.visitQueue (/home/arichiardi/git/js.spec/node_modules/babel-traverse/lib/context.js:150:16)
        at TraversalContext.visitSingle (/home/arichiardi/git/js.spec/node_modules/babel-traverse/lib/context.js:108:19)
        at TraversalContext.visit (/home/arichiardi/git/js.spec/node_modules/babel-traverse/lib/context.js:192:19)
        at Function.traverse.node (/home/arichiardi/git/js.spec/node_modules/babel-traverse/lib/index.js:114:17)
        at traverse (/home/arichiardi/git/js.spec/node_modules/babel-traverse/lib/index.js:79:12)
        at File.transform (/home/arichiardi/git/js.spec/node_modules/babel-core/lib/transformation/file/index.js:548:35)
        at /home/arichiardi/git/js.spec/node_modules/babel-core/lib/transformation/pipeline.js:50:19
        at File.wrap (/home/arichiardi/git/js.spec/node_modules/babel-core/lib/transformation/file/index.js:564:16)
        at Pipeline.transform (/home/arichiardi/git/js.spec/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
        at transpile (/home/arichiardi/git/js.spec/node_modules/babel-loader/lib/index.js:49:20)
        at Object.module.exports (/home/arichiardi/git/js.spec/node_modules/babel-loader/lib/index.js:171:20)
     @ ./lib/spec/index.js 1:521-544
     @ ./index.js
```

**Comment by arichiardi** [comment]
Ok reverted to use UglifyJS2 and harmony, it works now.
I have also a branch already for `babili` and will PR when they fix it.

**Comment by mattbishop** [comment]
@arichiardi Can you trigger a build again? I think you have to push a trivial change.

**Comment by arichiardi** [comment]
@prayerslayer bump! :smile:

**Comment by prayerslayer** [comment]
Sorry for the wait! I guess the change is reasonable, though I find your suggestion elsewhere to use Symbols also interesting. I feel there is potential to abandon classes in favor functions, but will need to investigate.

**Comment by arichiardi** [comment]
No problem and thanks for merging! Are you planning for a hot fix release by any chance? It would be awesome!

**Comment by prayerslayer** [comment]
Done, it's `1.0.0-4`.

**Pull request merged**
