### PR TITLE
Expose the predicate function to create Predicate specs from functions

### PR DESCRIPTION
**Pull request by mattbishop**
I know it isn't necessary to create a spec object for predicates but is is helpful for those cases where one is passing specs to other things in a codebase.

### CODE REVIEW

**Comment by arichiardi** [comment]
It looks good, but there are linting adjustments to make...

**Comment by arichiardi** [comment]
Sorry: 

```
/home/travis/build/prayerslayer/js.spec/lib/util.js
  19:39  error  Replace `specName` with `⏎········specName⏎······`  prettier/prettier
```

maybe we can discuss at some point to drop `prettier` linting.

**Comment by mattbishop** [comment]
Let's discuss it now because it isn't helping. I run `yarn lint` in the project locally and pass. Perhaps Travis uses a different ruleset?

**Comment by arichiardi** [comment]
I have had the same problem  a while ago and could not for the life of me understand what was wrong, let me try on my side

**Comment by mattbishop** [comment]
Another idea is to pin the versions of the dev tools for stability. It's likely my locally-installed `prettier` is different from what is in Travis. I'll submit a PR for that and see.

**Comment by mattbishop** [comment]
Pinning worked for me, at least I know I'm building with known dependencies: https://github.com/prayerslayer/js.spec/pull/60

**Comment by mattbishop** [comment]
I'll rebase after this merges: https://github.com/prayerslayer/js.spec/pull/60

**Comment by arichiardi** [comment]
Done

**Pull request merged**
