### PR TITLE
Adding assert() and explainStr() to match clojure.spec missing behaviour

### PR DESCRIPTION
**Pull request by mattbishop**
Fix for https://github.com/prayerslayer/js.spec/issues/15

Tested with `yarn test`.
It updated checked-in file `dist/js.spec.bundle.js` but I doubt you want that change in a PR.

### CODE REVIEW

**Comment by mattbishop** [comment]
Those coveralls messages is just me squashing commits down.

**Comment by prayerslayer** [comment]
I figured :grin: Just tell me when you're done! 👏

**Comment by mattbishop** [comment]
OK done.

**Comment by prayerslayer** [comment]
Looks good, thanks a lot! :sparkles:

**Pull request merged**
