### PR TITLE
map.conform() doesn't need to recreate the same key spec every time

### PR DESCRIPTION
**Pull request by mattbishop**
Usual random eslint/prettier changes

### CODE REVIEW

**Comment by arichiardi** [comment]
Some of the changes should already be on `master`: https://github.com/prayerslayer/js.spec/commit/371684502e0fd3e99cc456e951d61d44224d9d97

**Comment by arichiardi** [comment]
Sorry I see that basically the linting did change something from master that I fixed yesterday. I added `yarn prettier` for solving this very annoying issues.

**Comment by mattbishop** [comment]
I ran `yarn prettier` and this is the result.

**Comment by mattbishop** [comment]
Maybe I am picking up a different prettier config?

**Comment by arichiardi** [comment]
Uhm strange. In any case Travis is happy so I am going to merge this

**Pull request merged**
