### PR TITLE
Add reserved mangle option for js.spec predicates

### PR DESCRIPTION
**Pull request by arichiardi**
The patch avoids mangling of the main js.spec predicates, it also bumps uglifyjs-webpack-plugin to the latest version because of the recently added uglify-es support.

### CODE REVIEW

**Comment by arichiardi** [comment]
@prayerslayer ping and sorry for pinging :smile:

**Comment by prayerslayer** [comment]
Nah, sorry for being slow. Since you currently care more about this library than I do, I added you as collaborator which means you should have push access now.

**Comment by arichiardi** [comment]
Ah ah ok, thanks! I will keep the PR flow going :smile: I will still need to ask you to release, for instance after this one gets in, gonna merge now if no objections.

**Comment by arichiardi** [comment]
Done! If you have two minutes and can push a release it would be awesome :smile:

**Comment by prayerslayer** [comment]
Done and you should also have access to the npm module. Ping me if you have questions about anything :)

**Comment by arichiardi** [comment]
That is great thanks! @prayerslayer can you do a `git push --tags`? I am going to try this right.

**Pull request merged**
